---
title: "Time Series Basics"
documentclass: ctexart
output:
  rticles::ctex:
    fig_caption: yes
    number_sections: yes
    toc: yes
date: "2023-05-05"
always_allow_html: yes
---

# quakes

```{r}
x=scan("quakes.dat")
x=ts(x) #this makes sure R knows that x is a time series
plot(x, type="b") #time series plot of x with points marked as "o"
```

```{r}
library(astsa) # See note 1 below
lag1.plot(x,1) # Plots x versus lag 1 of x.
```

```{r}
acf(x, xlim=c(1,19)) # Plots the ACF of x for lags 1 to 19
```

```{r}
xlag1=lag(x,-1) # Creates a lag 1 of x variable. See note 2
y=cbind(x,xlag1) # See note 3 below
ar1fit=lm(y[,1]~y[,2])#Does regression, stores results object named ar1fit
summary(ar1fit) # This lists the regression results
```

```{r}
plot(ar1fit$fit,ar1fit$residuals) #plot of residuals versus fits
```

```{r}
acf(ar1fit$residuals, xlim=c(1,18)) # ACF of the residuals for lags 1 to 18
```

# cmort
```{r}
mort=scan("cmort.dat")
plot(mort, type="o") # plot of mortality rate
```

```{r}
mort=ts(mort)
mortdiff=diff(mort,1) # creates a variable = x(t) – x(t-1)
plot(mortdiff,type="o") # plot of first differences
```

```{r}
acf(mortdiff,xlim=c(1,24)) # plot of first differences, for 24 lags
mortdifflag1=lag(mortdiff,-1)
y=cbind(mortdiff,mortdifflag1) # bind first differences and lagged first differences
```

```{r}
mortdiffar1=lm(y[,1]~y[,2]) # AR(1) regression for first differences
summary(mortdiffar1) # regression results
```

```{r}
acf(mortdiffar1$residuals, xlim = c(1,24)) # ACF of residuals for 24 lags. 
```
